# Hydra base configuration file

defaults:
  - _self_
  - model: model
  - data: cifar100 # options: cifar100 / tiny_imagenet
  - logging: wandb # options: wandb, tensorboard, none

data_dir: /home/alex/data
genai_dir: /synthetic_cifar100_research/cifar100_512x512_master
genai_img_set: 1

# General
is_old_experiment: false # Whether to run the old experiment
seed: 42 # random seed for reproducability
device: cuda # CHANGE TO "cuda" IF YOU HAVE ONE
output_dir: /home/alex/repos/ms_project_2/results/ # Change this to your own path
embeddings_location: /home/alex/data/embeddings
logs_location: /home/alex/repos/ms_project/logs

# save_model: false # save the model after training